# yamllint disable-file
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "angular-dragdrop"
  description: "Drag and Drop for AngularJS (with Animation)"
  title: "angular dragdrop"
  tags:
    - emr
spec:
  type: "library"
  owner: "group:default/emr-tasy-framework-contributors"
  lifecycle: "production"
